### ISSUE TITLE
PushWeb: No pregunta si desea notificaciones Firefox 57.0 (quantum) 

### ISSUE THREAD

**Issue by pcor** [10darts/web-TendartsSDK#2]

**Comment by saruba** [comment]
Parece que es un problema con el evento de creación de device que no lo dispara.
Al cambiar el orden con que se registra el device se solucionara el problema, pero lo dejamos abierto de momento.
Se puede ejecutar manualmente desde la consola.

`Tendarts.subscribe()`

**Comment by pcor** [comment]
Lo  has cambiado en el código? Esta subido?

**Comment by saruba** [comment]
No, estoy en ello.

**Comment by pcor** [comment]
Ya me pregunta, se puede cerrar
