### ISSUE TITLE
No se marcan los abiertos

### ISSUE THREAD

**Issue by pcor** [10darts/web-TendartsSDK#3]
He mandado una campaña he pulsado en ella y me ha llevado a la página pero en la campaña aparecen 0 abiertos

**Comment by marcosgabarda** [comment]
@pcor En el título pones que no se marcan los recibidos, pero en la descripción dices que aparecen 0 abiertos, ¿a qué te refieres?

**Comment by pcor** [comment]
No se marcan los abiertos, los recibidos no se ven en la campaña

**Comment by marcosgabarda** [comment]
@pcor lo podrías haber mirado en el admin, que ahí sí se ven, por eso preguntaba, pero ok, hablamos de abiertos.

**Comment by pcor** [comment]
He comprobado que con la version 0.2 si se marcan los recibidos, en el admin, y los seguidos
